services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    command: redis-server --requirepass admin
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mysql_data:
  redis_data: